version: '3'

services:
  #
  # Ethereum mainnet geth
  #
  # https://hub.docker.com/r/ethereum/client-go
  # https://githwcat ub.com/Capgemini-AIE/ethereum-docker/blob/master/docker-compose-standalone.yml
  #

  # Secondary Ethereum instance
  geth:
    image: ethereum/client-go:stable
    restart: always
    container_name: geth
    network_mode: host
    # Set up JSON-RPC, GraphQL
    # Set up AuthRPC for Ethereum 2 beacon chain node to connect
    # HTTP port 127.0.0.1:10000 is proxyed with Caddy /etc/caddy/Caddyfile
    # that adds HTTP Basic auth.
    command: >
        --http
        --graphql
        --graphql.vhosts=*
        --http.addr 127.0.0.1
        --port 30302
        --http.port 10000
        --http.vhosts=*
        --authrpc.jwtsecret=/jwtsecret
        --authrpc.port 8553
        --authrpc.addr=0.0.0.0
        --authrpc.vhosts=vitalik4.tradingstrategy.ai
        --cache 8000
        --history.transactions 0
        --syncmode snap
    volumes:
      - /node/ethereum/geth:/root/.ethereum
      # ETH2 beacon chain node secret file for AuthRPC.
      # Share with your beacon client.
      # Generate this file: openssl rand -hex 32 > jwtsecret
      # and share to beacon chain node.
      - /node/ethereum/jwtsecret:/jwtsecret

  # Beacon chain node using Lighthouse.
  # This node does not publicly expose any RPC servers
  # and only connects to above nodes using authrpc.
  lighthouse:
    container_name: lighthouse
    image: sigp/lighthouse:latest
    restart: always
    # Pridileged needed because of how Lighthouse is setting file system permissions.
    privileged: true
    # Infura is used to boostrap the sync
    # https://ethereum.stackexchange.com/questions/135163/checkpoint-sync-source-for-ethereum-beacon-chain-node/135164#135164
    # See .env for infura URL

    # TODO: Disabled for now
    command: >
      lighthouse
       --network
       mainnet
       beacon
       --http
       --http-address=0.0.0.0
       --http-port=5052
       --http-allow-origin=*
       --execution-endpoint=http://vitalik4.tradingstrategy.ai:8553
       --execution-jwt=/jwtsecret
       --checkpoint-sync-url=https://mainnet.checkpoint.sigp.io 
    ports:
      - 9000:9000/tcp
      - 9000:9000/udp
      # Expose API port for Caddy to bind
      - 127.0.0.1:5052:5052
    environment:
    # Do a full backtrace when lighthouse crashes
      - RUST_BACKTRACE=full
    volumes:
      - /node/ethereum/lighthouse:/root/.lighthouse
      - /node/ethereum/jwtsecret:/jwtsecret
